# Generated by Django 5.0.2 on 2024-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('city', models.CharField(default='', max_length=65)),
                ('neighborhood', models.CharField(default='', max_length=65)),
                ('description', models.CharField(max_length=255)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('img_restaurant', models.ImageField(blank=True, default='', upload_to='restaurant/cover/img')),
            ],
        ),
    ]
